{% set name = "gloe" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gloe-{{ version }}.tar.gz
  sha256: 50b60e81d1a3048f8aad70e5ccc062ca75cac0d5f7af9542dc7ce770db91f843

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions >=4.7,<5.dev0

test:
  imports:
    - gloe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Gloe is a general-purpose library designed to guide developers in expressing their code as a flow. 
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://gloe.ideos.com.br/
  home: https://gloe.ideos.com.br/
  dev_url: https://github.com/ideos/gloe

extra:
  recipe-maintainers:
    - samirbraga
