{% set name = "gloe" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gloe-{{ version }}.tar.gz
  sha256: 83a3a8bc66929e7f5d2a0ed485878badd7996e1ce659916639a14625206ae057

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - typing-extensions >=4.7,<5.dev0
    - networkx >=3.1,<4.dev0

test:
  imports:
    - gloe
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Gloe (pronounced /ɡloʊ/, like "glow") is a general-purpose library made to help developers create, maintain, document, and test both operational and flow-oriented code.
  description: |
    Gloe (pronounced /ɡloʊ/, like "glow") is a general-purpose library made to help
    developers create, maintain, document, and test both operational and flow-oriented
    code. It is particularly useful in data science and machine learning pipelines, as
    well as in servers and scripts, or any area where there is a gap between the code
    and the logical business understanding. Gloe is not intended to be used across an
    entire application or to replace existing libraries. Instead, it is built to
    integrate with other tools and to address areas where the code complexity may be
    higher than expected.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://gloe.ideos.com.br/
  home: https://gloe.ideos.com.br/
  dev_url: https://github.com/ideos/gloe

extra:
  recipe-maintainers:
    - samirbraga
